name: allofine
description: "C'est un peu comme un AlloCiné mais avec le F de Flutter... ;)"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^13.0.0
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.8.1
  provider: ^6.1.1

dev_dependencies:
  build_runner: ^2.4.7

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
